### ISSUE TITLE
Bug: Video getting black when using the interface

### ISSUE THREAD

**Issue by kurisutofu** [webosbrew/youtube-webos#203]
## YTAF information
  - YTAF version: 0.3.4

## TV information
  - webOS version: 4.10.0-17
  - Firmware version: 05.40.45
  - Model: OLED55C9PJA
  - OTA ID: HE_DTV_W19O_AFABJAAAo18
  - SoC: 018

## Issue description

When the interfaces shows on the screen, be it when pausing the video, fast forwarding, or rewinding, the video becomes black. The sound still works and the video continues (unless the action was to pause the video).
Could it be that the interface is overlaid on top of the video and lost its transparency property?
Can it be fixed?

Please note that I tried killing the app and opening again, uninstalling/re-installing, and it didn't work.
The YTAF menu displays fine when pressing the green button and funnily, it does not lead the video to turn black.

Displaying the comment panel works fine and the video is visible, though it is black until showing the comments.

Step to reproduce:
1 - Start a video
2 - Pause the video
or
2 - Move the timeline (fast forward or rewind)
or
2 - Press the up arrow

**Comment by putridpete** [comment]
I was actually on my way to create this very same thread when I stumbled upon this one, so I can confirm experiencing this issue too.

TV information (non rooted, using dev mode):

    webOS version: 8.3.1-3607
    Firmware version: 03.31.82
    Model: 50UR8050AUA

Seems as if Youtube change things around again.

**Comment by Superspongo** [comment]
Thanks for reporting. I have the same issue on a 55C8.

**Comment by Dsilvabr** [comment]
Me too.

webOS version: 4.10.0-17
Firmware version: 05.40.45

**Comment by wiz0u** [comment]
Same here 
05.50.45
4.4.0

**Comment by K4M1L41** [comment]
Me too 
5.5.0-19
4.50.90
Oled CX

**Comment by marianmargraf** [comment]
+1 on my OLED B7 55

06.10.30
webOS 3.9.2

**Comment by Inkrm** [comment]
same here
webOS 04.40.92
NANO766QA

**Comment by bebach8** [comment]
Can confirm same symptoms
55UN80003LA
webOS 5.3.0-2204

**Comment by rogodra** [comment]
I have the same problem for two days.

55NANO916PA
webOS version: 6.4.0
Firmware version: 03.40.82

and

43UP76906LE
webOS version: 6.4.0
Firmware version: 03.40.82

**Comment by marianmargraf** [comment]
Starting today, Google is rolling out updates to the YouTube UI on web, mobile and TV. This might be a reason for this issue.
https://blog.youtube/news-and-events/youtube-features-and-updates-2024/

**Comment by the-nexi** [comment]
Reporting the same issue.

**Comment by throwaway96** [comment]
@kurisutofu 

Thanks for the detailed report. I appreciate you providing platform and version information. Since I don't use YTAF, I wasn't aware of this issue.

@marianmargraf

Thank you. This is interesting and (potentially) helpful. 

We don't need any more "me too" posts, except maybe a single report each for webOS 1, 2, 3.0, and 9.

Since at least webOS 3.5 through 8 are affected, presumably so are the rest. I assume Google changed something on their end that broke YTAF for everyone. I would like to know if the stock WAM YT app still works.

I will look into this when I have time, but it would be great if someone who actually uses YTAF (and has free time) could step up to maintain it.

**Comment by okkkkoo** [comment]
Me too

**Comment by cremor** [comment]
@throwaway96 I assume this can fix it for YTAF too: https://github.com/reisxd/TizenTube/commit/c1f92b0a69a242124c6e125ade320f70821779e4

**Comment by Avelayy** [comment]
@cremor can we apply this fix by yourself?

**Comment by atomjack** [comment]
@throwaway96 I've submitted a PR to fix this issue, per @cremor 's suggestion. I tested it on my TV and it works fine.

**Comment by throwaway96** [comment]
Resolved by #204.

**Comment by Dsilvabr** [comment]
I am sorry, I am new here, how is this fixed? I uninstall e reinstall the app and still the same, I need to do something? Sorry if it's a stupid question.

**Comment by Avelayy** [comment]
@Dsilvabr u can download fixed app from here: https://github.com/webosbrew/youtube-webos/actions/runs/11412869119
Then install it using developer manager for lg using PC

**Comment by throwaway96** [comment]
Please try this: <https://github.com/webosbrew/youtube-webos/releases/tag/v0.3.5-rc1>

**Comment by Dsilvabr** [comment]
> Please try this: https://github.com/webosbrew/youtube-webos/releases/tag/v0.3.5-rc1

I did what [Avelayy](https://github.com/Avelayy) told me to do and worked, but thx!  :D

**Comment by wiz0u** [comment]
> Please try this: https://github.com/webosbrew/youtube-webos/releases/tag/v0.3.5-rc1

worked. (is it normal the ipk file is still named 0.3.4 ?)

**Comment by cremor** [comment]
> Please try this: https://github.com/webosbrew/youtube-webos/releases/tag/v0.3.5-rc1

This fixes the issue, thanks!
But am I stupid or is there now a transparent background (which darkens the video) when a side panel (comments or settings) is open, which hasn't been there before?

**Comment by cremor** [comment]
Another thing: I'm not sure, but this might have broken shorts. There is now a grey area over the short display area which hasn't been there in the previous version.

**Comment by throwaway96** [comment]
@cremor

Does this happen even with "Remove Shorts from subscriptions" disabled?

**Comment by Avelayy** [comment]
@throwaway96 i have newest version YTAF installed and i can confirm that there is a grey are over the shorts in home page.

**Comment by Avelayy** [comment]
@throwaway96 this is how it looks like 
![IMG_20241019_183646__01](https://github.com/user-attachments/assets/77ec4146-6a01-4f31-acfa-30e07a077c50)

**Comment by wiz0u** [comment]
> @cremor
> 
> Does this happen even with "Remove Shorts from subscriptions" disabled?

For me, this option works well in the subscriptions page.
in the home page, whether option is set or not, the Shorts section is present but the thumbnails are absents. Only their title appear.

**Comment by cremor** [comment]
> Does this happen even with "Remove Shorts from subscriptions" disabled?

Yes.

**Comment by Dsilvabr** [comment]
That missing thumbnails on shorts was happening prior to the fix, I notice that about 7 days ago.

**Comment by throwaway96** [comment]
@Dsilvabr

If that's true then I'm just going to release it as-is.

**Comment by cremor** [comment]
I don't know about thumbnails on the home screen. But actual playback of shorts worked before the upgrade.

**Comment by Avelayy** [comment]
@throwaway96 missing thumbnails on shorts was happening before yesterday hotfix

**Comment by cremor** [comment]
> Yes, and they still play, in the Home, subscription and individual channel, shorts are playing normaly

Not for me. If it works for you then I don't know why it doesn't for me.

**Comment by throwaway96** [comment]
Please open a separate issue and provide version and platform information for new problems in 0.3.5-rc1.

**Comment by Kneit0r** [comment]
This was the same issue a while back, someone added a dirty transparancy hack back then, probably not working anymore because youtubes ui code got changed again.
